Add backup and rollback steps to Terraform commands in CD workflow

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -55,6 +55,7 @@ jobs:
       - name: Terraform Commands
         run: |
           terraform init
+          terraform state pull > terraform.tfstate.backup
           terraform validate
           terraform plan -out=tfplan -var 'sql_admin_password=${{ secrets.SA_PASSWORD }}' -var 'image_tag=${{ inputs.image_tag }}'
           terraform apply -auto-approve tfplan
@@ -64,6 +65,14 @@ jobs:
           ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
           ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
           ARM_USE_OIDC: true
+
+      - name: Check Apply Result
+        if: failure()
+        run: |
+          echo "Terraform apply failed. Reverting to previous state..."
+          terraform state push terraform.tfstate.backup
+          exit 1
+        working-directory: ./terraform/staging
 
       - name: Capture Terraform Outputs
         id: capture_outputs
@@ -199,6 +208,7 @@ jobs:
       - name: Terraform Commands
         run: |
           terraform init
+          terraform state pull > terraform.tfstate.backup
           terraform validate
           terraform plan -out=tfplan -var 'sql_admin_password=${{ secrets.SA_PASSWORD }}' -var 'image_tag=${{ inputs.image_tag }}'
           terraform apply -auto-approve tfplan
@@ -208,6 +218,14 @@ jobs:
           ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
           ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
           ARM_USE_OIDC: true
+
+      - name: Check Apply Result
+        if: failure()
+        run: |
+          echo "Terraform apply failed. Reverting to previous state..."
+          terraform state push terraform.tfstate.backup
+          exit 1
+        working-directory: ./terraform/production
 
       - name: Capture Terraform Output
         id: output
