Remove unnecessary checkout step and add error handling for Docker commands in CD workflow

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -66,9 +66,6 @@ jobs:
       url: http://tsvi.eastus.cloudapp.azure.com
     needs: [staging-end2end-tests]
     steps:
-      - name: Checkout repository
-        uses: actions/checkout@v3
-
       - name: 'Az CLI Login via OIDC'
         uses: azure/login@v1.4.6
         with:
@@ -84,6 +81,6 @@ jobs:
             export ASPNETCORE_URLS='${{ secrets.ASPNETCORE_URLS }}'
             export TAG='${{ inputs.image_tag }}'
             cd /home/azureuser
-            docker compose pull webapp
-            docker compose up -d --no-deps --build webapp
+            docker compose pull webapp || { echo 'Failed to pull the image' ; exit 1; }
+            docker compose up -d --no-deps --build webapp || { echo 'Failed to start the container' ; exit 1; }
           "
